# ==========================================
# COLAB CELL 4: LAYER 1 ALPHA ENGINE (14.py)
# ==========================================

import polars as pl
import warnings

from ml4t.engineer import compute_features
from ml4t.engineer.features.cross_asset import (
    beta_to_market,
    relative_strength_index_spread,
    volatility_ratio
)
from ml4t.engineer.features.fdiff import find_optimal_d, ffdiff
from ml4t.engineer.config import LabelingConfig
from ml4t.engineer.labeling import triple_barrier_labels  # 100% Native Labeler
from ml4t.specs import (
    MarketDataSpec,
    ArtifactStorage,
    ArtifactProvenance,
    read_spec_payload,
    write_spec_payload
)

warnings.filterwarnings("ignore", message=".*cyclical_encode.*")

def generate_features_and_labels():
    print("--- STEP 1: Loading Dollar Clock Data ---")
    base_spec = MarketDataSpec.from_mapping(read_spec_payload("solusdt_contract.yaml"))

    hive_path = f"{base_spec.storage.path}/crypto_bars_SOLUSDT/**/*.parquet"
    df = pl.scan_parquet(hive_path, hive_partitioning=True).collect().sort("timestamp")

    print(f"✅ Loaded {df.shape:,} synchronized dollar bars.")

    # ==========================================
    # 2. TARGET NEUTRALIZATION
    # ==========================================
    print("--- STEP 2: Calculating Returns & Idiosyncratic Residual ---")
    # Generate the base returns needed for beta neutralization
    df = df.with_columns(
        pl.col("close").pct_change().alias("asset_ret"),
        pl.col("btc_close").pct_change().alias("market_ret")
    ).drop_nulls()

    # Calculate Beta and residual idiosyncratic returns
    df = beta_to_market(df, asset_col="asset_ret", market_col="market_ret", window=100)

    # ==========================================
    # 3. FEATURE ENGINEERING
    # ==========================================
    print("--- STEP 3: Engineering Cross-Asset & FFD Features ---")
    # Base technicals
    df = relative_strength_index_spread(df, close_col="close", window1=14, window2=28)
    df = volatility_ratio(df, close_col="close", window1=14, window2=28)

    # Fractional Differentiation to preserve memory while achieving stationarity
    d_val = find_optimal_d(df["rsi_spread"].drop_nulls().to_numpy())
    print(f"Optimal Fractional D value: {d_val:.4f}")
    df = ffdiff(df, col="rsi_spread", d=d_val, alias="rsi_spread_ffd")

    # Drop nulls generated by rolling windows to prepare for ML ingestion
    df = df.drop_nulls()

    # ==========================================
    # 3.6 PRIMARY SIGNAL (QUICK UPSIDE TEST)
    # ==========================================
    print("--- STEP 3.6: Generating Primary Signal ---")
    # Convert from "guessing market direction" to "evaluating prediction success".
    # For this quick test, we only "intend" to trade Long (1) when short-term momentum is positive.
    df = df.with_columns(
        pl.when(pl.col("rsi_spread_ffd") > 0).then(1)
        .otherwise(0) # 0 means sit out, no trade taken
        .alias("side")
    )

    # ==========================================
    # 4. TRIPLE BARRIER LABELING (PREDICTION SUCCESS)
    # ==========================================
    print("--- STEP 4: Native Meta-Labeling ---")

    tbm_config = LabelingConfig.triple_barrier(
        upper_barrier=0.003,
        lower_barrier=0.003,
        max_holding_period=4
        # DO NOT hardcode side=0 here. The TBM dynamically reads the primary 'side' column.
    )

    # We only apply the TBM computationally to rows where we actually signaled a trade
    trade_signals = df.filter(pl.col("side") == 1)

    labeled_df = triple_barrier_labels(
        data=trade_signals,
        config=tbm_config,
        price_col="close",
        high_col="high",             
        low_col="low",               
        timestamp_col="timestamp",
        side_col="side",                               # <--- INJECT PRIMARY SIGNAL HERE
        calculate_uniqueness=True,                     
        uniqueness_weight_scheme="returns_uniqueness"  
    )

    # ==========================================
    # 4.5 TODO / REMINDER: FUTURE ARCHITECTURE UPGRADES
    # ==========================================
    # REMINDER: The original "Binary Conversion" block was DELETED here. 
    # Because we passed `side_col="side"` to the TBM in Step 4, it natively outputs 
    # based on whether our primary signal succeeded or failed.
    # LightGBM will compile this flawlessly.
    # 
    # TODO LATER:
    # If you want to switch to a symmetric model (-1, 0, 1) to evaluate Shorts:
    # 1. Update Step 3.6 to generate -1s for short entries (e.g., when rsi_spread_ffd < 0).
    # 2. Update the `trade_signals` filter to: df.filter(pl.col("side") != 0)
    # 3. The TBM will still output binary prediction success for both Longs and Shorts natively.

    # ==========================================
    # 5. STORAGE & CONTRACT
    # ==========================================
    print("--- STEP 5: Storing Features & Labels ---")
    output_parquet = "SOLUSDT_ml_ready.parquet"
    labeled_df.write_parquet(output_parquet)

    features_spec = MarketDataSpec(
        artifact_id="solusdt_features_and_labels_v1",
        schema=base_spec.schema,
        semantics=base_spec.semantics,
        storage=ArtifactStorage(path=output_parquet, format="parquet"),
        provenance=ArtifactProvenance(source_artifacts=(base_spec.artifact_id,))
    )

    write_spec_payload(features_spec.to_dict(), "solusdt_features_contract.yaml")
    print(f"✅ Features, Native Labels & Contract successfully saved to {output_parquet}")

if __name__ == "__main__":
    generate_features_and_labels()
